# Generated by Django 3.2.5 on 2021-08-09 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pseudo UUID')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving District')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving State')),
                ('pin_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving PINCode')),
                ('govt_agency_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Govt. Agency ID')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(default=18, verbose_name='Age')),
                ('secret_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Secret Code')),
                ('static_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Static Key')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vaccination ID')),
                ('pseudo_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pseudo UUID')),
                ('center_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Center ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 8, 9, 14, 34, 3, 781387, tzinfo=utc), verbose_name='Vaccination Timestamp')),
                ('health_conditions', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Health Conditions')),
                ('vaccinator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vaccinator Name')),
                ('vaccine_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vaccine Name')),
                ('dose_number', models.IntegerField(default=0, verbose_name='Dose Number')),
            ],
        ),
    ]
