# Generated by Django 3.2.5 on 2021-08-09 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaccination Timestamp'),
        ),
    ]
