# Generated by Django 3.2.5 on 2021-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vaccination_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='doses',
            field=models.IntegerField(default=0, verbose_name='Doses'),
        ),
    ]
