# Generated by Django 3.2.5 on 2021-08-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Center ID')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving District')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving State')),
                ('pin_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving PINCode')),
                ('govt_agency_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Govt. Agency ID')),
                ('static_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Static Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='GovtAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving District')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving State')),
                ('pin_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serving PINCode')),
                ('master_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Master Key')),
                ('serving_centers', models.ManyToManyField(to='users.Center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
